// GENERATED by packages/schema/gen.mjs. Do not edit. Source: strategy.schema.json

export type Regime = "trend" | "range" | "compression" | "high_vol" | "event";
/**
 * Input name, dotted input field (bb.upper), bar field (open/high/low/close/volume) or a number
 */
export type Operand = string | number;

/**
 * A complete, testable rule set. Single source of truth for web and engine.
 */
export interface Strategy {
  /**
   * slug_vN, immutable once validated
   */
  strategy_id: string;
  name: string;
  version: number;
  parent_id: string | null;
  market: "NSE_EQ" | "NSE_FO";
  /**
   * User-chosen symbols only
   */
  instruments: string[];
  timeframe: "1m" | "3m" | "5m" | "15m" | "30m" | "1h" | "1D";
  session: {
    start: string;
    end: string;
    flat_at_close: boolean;
  };
  regime_affinity: Regime[];
  inputs: {
    [k: string]: Input;
  };
  entry_long: Condition[];
  entry_short: Condition[] | null;
  trigger: {
    type: "next_bar_open" | "break_of_signal_bar" | "bar_close" | "limit";
    offset_pct?: number;
  };
  stop: {
    type: "signal_bar" | "swing" | "atr" | "indicator" | "fixed_pct";
    params: {};
  } | null;
  targets: {
    type: "rr" | "indicator" | "fixed_pct";
    value: number;
    /**
     * input name when type = indicator
     */
    ref?: string;
  }[];
  trailing: {
    type: "none" | "indicator" | "atr" | "breakeven_after_r";
    params: {};
  };
  time_exit: {
    max_bars?: number;
    at_time?: string;
  };
  risk: {
    min_rr_after_costs: number;
    max_equity_risk_pct: number;
    max_trades_per_day: number;
  };
  automation_permission: "paper_only" | "mentor_only" | "blocked";
  /**
   * Populated by the mentor; non-empty blocks testable
   */
  ambiguity_flags: string[];
  version_locked: boolean;
}
export interface Input {
  indicator:
    | "sma"
    | "ema"
    | "rsi"
    | "macd"
    | "bbands"
    | "atr"
    | "supertrend"
    | "donchian"
    | "vwap"
    | "williams_r"
    | "psar"
    | "ichimoku"
    | "pivots"
    | "cpr"
    | "swing"
    | "volume_ratio"
    | "adx"
    | "heikin_ashi";
  params: {};
}
export interface Condition {
  lhs: Operand;
  op: ">" | "<" | ">=" | "<=" | "==" | "crosses_above" | "crosses_below" | "rising" | "falling";
  rhs: Operand;
  lookback?: number;
}
