// Generates TS types (src/types.ts) and pydantic models (services/engine/engine/schema/strategy.py)
// from strategy.schema.json. Run: pnpm gen
import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schema = JSON.parse(readFileSync(resolve(here, "strategy.schema.json"), "utf8"));
const ts = await compile(schema, "Strategy", {
  bannerComment: "// GENERATED by packages/schema/gen.mjs. Do not edit. Source: strategy.schema.json",
  additionalProperties: false,
  style: { singleQuote: false },
});
writeFileSync(resolve(here, "src/types.ts"), ts);
console.log("wrote src/types.ts");

const out = resolve(here, "../../services/engine/engine/schema/strategy.py");
const cmd = [
  "python -m datamodel_code_generator --input strategy.schema.json --input-file-type jsonschema",
  `--output "${out}" --output-model-type pydantic_v2.BaseModel --use-standard-collections --use-union-operator`,
  "--target-python-version 3.12 --disable-timestamp --class-name Strategy --use-schema-description --field-constraints",
].join(" ");
try {
  execSync(cmd, { stdio: "inherit", cwd: here });
  console.log("wrote engine/schema/strategy.py");
} catch {
  console.error("pydantic generation failed. Install with: pip install datamodel-code-generator");
  process.exit(1);
}
