# generated by datamodel-codegen:
#   filename:  strategy.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Market(StrEnum):
    NSE_EQ = 'NSE_EQ'
    NSE_FO = 'NSE_FO'


class Instrument(RootModel[str]):
    root: str = Field(..., pattern='^[A-Z0-9&-]{1,20}$')


class Timeframe(StrEnum):
    field_1m = '1m'
    field_3m = '3m'
    field_5m = '5m'
    field_15m = '15m'
    field_30m = '30m'
    field_1h = '1h'
    field_1D = '1D'


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: str = Field(..., pattern='^[0-2][0-9]:[0-5][0-9]$')
    end: str = Field(..., pattern='^[0-2][0-9]:[0-5][0-9]$')
    flat_at_close: bool


class Type(StrEnum):
    next_bar_open = 'next_bar_open'
    break_of_signal_bar = 'break_of_signal_bar'
    bar_close = 'bar_close'
    limit = 'limit'


class Trigger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    offset_pct: float | None = None


class Type1(StrEnum):
    signal_bar = 'signal_bar'
    swing = 'swing'
    atr = 'atr'
    indicator = 'indicator'
    fixed_pct = 'fixed_pct'


class Stop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1
    params: dict[str, Any]


class Type2(StrEnum):
    rr = 'rr'
    indicator = 'indicator'
    fixed_pct = 'fixed_pct'


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type2
    value: float
    ref: str | None = Field(None, description='input name when type = indicator')


class Type3(StrEnum):
    none = 'none'
    indicator = 'indicator'
    atr = 'atr'
    breakeven_after_r = 'breakeven_after_r'


class Trailing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type3
    params: dict[str, Any]


class TimeExit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_bars: int | None = Field(None, ge=1)
    at_time: str | None = Field(None, pattern='^[0-2][0-9]:[0-5][0-9]$')


class Risk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    min_rr_after_costs: float = Field(..., ge=0.0)
    max_equity_risk_pct: float = Field(..., ge=0.0, le=1.0)
    max_trades_per_day: int = Field(..., ge=1)


class AutomationPermission(StrEnum):
    paper_only = 'paper_only'
    mentor_only = 'mentor_only'
    blocked = 'blocked'


class Regime(StrEnum):
    trend = 'trend'
    range = 'range'
    compression = 'compression'
    high_vol = 'high_vol'
    event = 'event'


class Indicator(StrEnum):
    sma = 'sma'
    ema = 'ema'
    rsi = 'rsi'
    macd = 'macd'
    bbands = 'bbands'
    atr = 'atr'
    supertrend = 'supertrend'
    donchian = 'donchian'
    vwap = 'vwap'
    williams_r = 'williams_r'
    psar = 'psar'
    ichimoku = 'ichimoku'
    pivots = 'pivots'
    cpr = 'cpr'
    swing = 'swing'
    volume_ratio = 'volume_ratio'
    adx = 'adx'
    heikin_ashi = 'heikin_ashi'


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    indicator: Indicator
    params: dict[str, Any]


class Operand1(RootModel[str]):
    root: str = Field(
        ...,
        description='Input name, dotted input field (bb.upper), bar field (open/high/low/close/volume) or a number',
        pattern='^[a-z][a-z0-9_]*(\\.[a-z0-9_]+)?(\\[-?[0-9]+\\])?$',
    )


class Operand(RootModel[Operand1 | float]):
    root: Operand1 | float = Field(
        ...,
        description='Input name, dotted input field (bb.upper), bar field (open/high/low/close/volume) or a number',
    )


class Op(StrEnum):
    field_ = '>'
    field__1 = '<'
    field__ = '>='
    field___1 = '<='
    field___2 = '=='
    crosses_above = 'crosses_above'
    crosses_below = 'crosses_below'
    rising = 'rising'
    falling = 'falling'


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lhs: Operand
    op: Op
    rhs: Operand
    lookback: int | None = Field(None, ge=1)


class Strategy(BaseModel):
    """
    A complete, testable rule set. Single source of truth for web and engine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    strategy_id: str = Field(
        ...,
        description='slug_vN, immutable once validated',
        pattern='^[a-z0-9_]+_v[0-9]+$',
    )
    name: str = Field(..., max_length=80, min_length=1)
    version: int = Field(..., ge=1)
    parent_id: str | None
    market: Market
    instruments: list[Instrument] = Field(..., description='User-chosen symbols only')
    timeframe: Timeframe
    session: Session
    regime_affinity: list[Regime]
    inputs: dict[constr(pattern=r'^[a-z][a-z0-9_]*$'), Input]
    entry_long: list[Condition]
    entry_short: list[Condition] | None
    trigger: Trigger
    stop: Stop | None
    targets: list[Target]
    trailing: Trailing
    time_exit: TimeExit
    risk: Risk
    automation_permission: AutomationPermission
    ambiguity_flags: list[str] = Field(
        ..., description='Populated by the mentor; non-empty blocks testable'
    )
    version_locked: bool
